// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAaLpQDeNM8PrzPSPzF305mkSVl0CHVZE',
    appId: '1:585077968144:android:fc613c4a8cab17387fe995',
    messagingSenderId: '585077968144',
    projectId: 'gp2-watad',
    storageBucket: 'gp2-watad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwGE0-2pQIwT-LTGHec70r7IH6DRlhn6w',
    appId: '1:585077968144:ios:e2617e637e961a247fe995',
    messagingSenderId: '585077968144',
    projectId: 'gp2-watad',
    storageBucket: 'gp2-watad.firebasestorage.app',
    iosBundleId: 'com.example.gp2Watad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07jH6PtaRyne5HHxBiBbvOvX6tQHl3eA',
    appId: '1:585077968144:web:d247ad1924a3fee57fe995',
    messagingSenderId: '585077968144',
    projectId: 'gp2-watad',
    authDomain: 'gp2-watad.firebaseapp.com',
    storageBucket: 'gp2-watad.firebasestorage.app',
    measurementId: 'G-TLBNBEN3C0',
  );

}